apiVersion: v1
kind: Service
metadata:
  name: mweb-service
  labels:
    env: dev
spec:
  selector:
    env: dev
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
  type: NodePort