apiVersion: v1
kind: Service
metadata:
  name: html-servive
  labels:
    app: myapp-service

spec:
  selector:
    env: production
  type: NodePort
  ports:
    - nodePort: 30000
      port: 81
      targetPort: 80

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: html-con
      labels:
        env: production
    spec:
      containers:
      - name: html-con
        image: httpd
        volumeMounts:
        - name: web-vol1
          mountPath: /usr/local/apache2/htdocs 

      volumes:
      - name: web-vol1
        persistentVolumeClaim:
           claimName: html-pvc
        
