apiVersion: v1
kind: Service
metadata:
  name: html-servive
  labels:
   app: myapp-service

spec:
  selector:
    env: production
  type: NodePort
  ports:
    - nodePort: 30000
      port: 81
      targetPort: 80


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: html-pod
      labels:
        env: production
    spec:
      containers:
      - name: "html-con"
        image: "httpd"
        volumeMounts:
        - name: html-vol
          mountPath: "/usr/local/apache2/htdocs"
      volumes:
      - name: html-vol
        hostPath:
             path: "/home/docker/test"
---

